//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 UUPAssistant.rc 使用
//
#define IDR_MENU                        102
#define String_DirChoice                1001
#define String_UUPDir                   1002
#define String_TempDir                  1003
#define String_TempDirDescription       1004
#define String_Edition                  1005
#define String_ImageName                1006
#define String_AdditionEditions         1007
#define String_Version                  1008
#define String_SystemLanguage           1009
#define String_Architecture             1010
#define String_ESDFile                  1011
#define String_Branch                   1012
#define String_SelectEdition            1013
#define String_NotEmpty                 1014
#define String_TempDirExists            1015
#define String_CannotWrite              1016
#define String_VolumeNotNTFS            1017
#define String_NoEditionSelected        1018
#define String_ProcessingRefESDs        1019
#define String_ProcessingFile           1020
#define String_ExpandingCab             1021
#define String_CapturingESD             1022
#define String_Cleaning                 1023
#define String_InplaceInstallation      1024
#define String_CreateImage              1025
#define String_HigherVersion            1026
#define String_NonupgradableEdition     1027
#define String_Purpose                  1028
#define String_DifferentArchitecture    1029
#define String_Browse                   1030
#define String_Next                     1031
#define String_Wait                     1032
#define String_Cancel                   1033
#define String_Notice                   1034
#define String_InstallWindows           1035
#define String_PartSel                  1036
#define String_Updating                 1037
#define String_ComError                 1038
#define String_Disk                     1039
#define String_Number                   1040
#define String_Letter                   1041
#define String_Size                     1042
#define String_Offset                   1043
#define String_PartStyle                1044
#define String_Refresh                  1045
#define String_Filesystem               1046
#define String_Label                    1047
#define String_Detail                   1048
#define String_GPTDetail                1049
#define String_MBRDetail                1050
#define String_True                     1051
#define String_False                    1052
#define String_ESP                      1053
#define String_BDP                      1054
#define String_MSReserved               1055
#define String_MSRecovery               1056
#define String_FreeSpace                1057
#define String_SystemPart               1058
#define String_PagePart                 1059
#define String_NoEnoughSpace            1060
#define String_SelectESP                1061
#define String_DontBoot                 1062
#define String_SetESPs                  1063
#define String_SelectFATPart            1064
#define String_Okay                     1065
#define String_InstallUpdates           1066
#define String_Add                      1067
#define String_Remove                   1068
#define String_BrowseDir                1069
#define String_SetPSF                   1070
#define String_AddUpdates               1071
#define String_File                     1072
#define String_Path                     1073
#define String_RemoveThis               1074
#define String_RemoveSelected           1075
#define String_RemoveAll                1076
#define String_UpdateFile               1077
#define String_FullPath                 1078
#define String_UpdatePathDetail         1079
#define String_FormatOptions            1080
#define String_Force                    1081
#define String_Quick                    1082
#define String_AddApps                  1083
#define String_AppPackage               1084
#define String_AppBundle                1085
#define String_Recurse                  1086
#define String_ForceUnsigned            1087
#define String_AddDrv                   1088
#define String_Removable                1089
#define String_AssignLetters            1090
#define String_SetLetters               1091
#define String_Dynamic                  1092
#define String_Step                     1093
#define String_CurrentSystemLetter      1094
#define String_Type                     1095
#define String_Set                      1096
#define String_SimpleVolume             1097
#define String_SpanVolume               1098
#define String_StripeVolume             1099
#define String_MirrorVolume             1100
#define String_ParityVolume             1101
#define String_NoLetterSelected         1102
#define String_Empty                    1103
#define String_SetVM                    1104
#define String_SetPage                  1105
#define String_CustomizePage            1106
#define String_SysMgmtPage              1107
#define String_NoPage                   1108
#define String_InvalidPageSize          1109
#define String_PageSetting              1110
#define String_VMSetting                1111
#define String_VMSysAutoMgmt            1112
#define String_VMSysMgmtDescription     1113
#define String_InitSize                 1114
#define String_MaxSize                  1115
#define String_OOBESettings             1116
#define String_SkipOOBE                 1117
#define String_EnableAdministrator      1118
#define String_SkipEULA                 1119
#define String_HideOnlineAccountScreens 1120
#define String_AddUser                  1121
#define String_RemoveUser               1122
#define String_AutoLogonOnce            1123
#define String_EnableAutoLogon          1124
#define String_SkipNetworkSetup         1125
#define String_ComputerName             1126
#define String_RegisteredOwner          1127
#define String_RegisteredOrganization   1128
#define String_AdministratorPassword    1129
#define String_User                     1130
#define String_AddUsers                 1131
#define String_UserName                 1132
#define String_Password                 1133
#define String_DisplayName              1134
#define String_Group                    1135
#define String_LogonSetPassword         1136
#define String_Description              1137
#define String_NoUsers                  1138
#define String_NoUserToLogon            1139
#define String_UserAccountType          1140
#define String_Administrator            1141
#define String_StandardUser             1142
#define String_InvalidUserName          1143
#define String_InvalidComputerName      1144
#define String_UserExisting             1145
#define String_RetypePassword           1146
#define String_DifferentPasswords       1147
#define String_Formatting               1148
#define String_UnableToSelectPart       1149
#define String_NeedFreeLetter           1150
#define String_Installing               1151
#define String_ApplyingImage            1152
#define String_InstallingFeatures       1153
#define String_InstallingUpdates        1154
#define String_InstallingSoftware       1155
#define String_ApplyingSettings         1156
#define String_AfterInstallation        1157
#define String_Shutdown                 1158
#define String_Reboot                   1159
#define String_Quit                     1160
#define String_ApplyingImageState       1161
#define String_InstallingDotNetFx3      1162
#define String_ExportingWinRe           1163
#define String_SwitchingEdition         1164
#define String_InstallingUpdateState    1165
#define String_InstallingAppState       1166
#define String_AddingDriverState        1167
#define String_ApplyingRegSettings      1168
#define String_RebuildingBoot           1169
#define String_PreparingFile            1170
#define String_EnableFeature            1171
#define String_OpenDismSession          1172
#define String_ExportingImage           1173
#define String_ImageIndex               1174
#define String_AddPackage               1175
#define String_ExpandingPSF             1176
#define String_Succeeded                1177
#define String_Failed                   1178
#define String_InstallingAppx           1179
#define String_AddingDriver             1180
#define String_CloseDismSession         1181
#define String_LoadRegistry             1182
#define String_UnloadRegistry           1183
#define String_RegKey                   1184
#define String_RegValue                 1185
#define String_Inf                      1186
#define String_AboutToShutdown          1187
#define String_AboutToReboot            1188
#define String_AboutToQuit              1189
#define String_ApplyUnattend            1190
#define String_Installed                1191
#define String_FailedButNoReasons       1192
#define String_ReopenDismSession        1193
#define String_CopyingBootFiles         1194
#define String_ConfiguringBCD           1195
#define String_LoadingBootInfo          1196
#define String_TargetPath               1197
#define String_BootPath                 1198
#define String_NotVolumeRoot            1199
#define String_VolumeFreeSpaceNotEnough 1200
#define String_FoundSystemFiles         1201
#define String_ReFSVolume               1202
#define String_FilesystemNotSupported   1203
#define String_BootMode                 1204
#define String_SetActiveParts           1205
#define String_SetBootRecords           1206
#define String_Active                   1207
#define String_ActivePartSetting        1208
#define String_BootRecordsSetting       1209
#define String_SetRecParts              1210
#define String_SettingRecParts          1211
#define String_OnlySupportGPTRecParts   1212
#define String_InstallREOnSysPart       1213
#define String_InstallRe                1214
#define String_CancelReInstallation     1215
#define String_REIsNotAvaliable         1216
#define String_ConfiguringReAgent       1217
#define String_SelectBootPart           1218
#define String_SetSystemPartAsBootPart  1219
#define String_BootFromVHD              1220
#define String_UseBootEX                1221
#define String_LearnMoreAboutBootEX     1222
#define String_FormatAsReFS             1223
#define String_CannotFormatAsReFS       1224
#define String_UnableToFormatAsReFS     1225
#define String_CannotBootFromReFSunderLegacy 1226
#define String_ViewAppxFeatures         1227
#define String_InstallingAppxFeatures   1228
#define String_WillDisableOthers        1229
#define String_InstallingAppxFeature    1230
#define String_StubOptionInstallFull    1231
#define String_StubOptionTip            1232
#define String_NotEnoughFreeSpace       1233
#define String_CustomizeSystemUpgrade   1234
#define String_Preparing                1235
#define String_PreventUpdating          1236
#define String_ConfiguringSafeOS        1237
#define String_WorkingOnMigration       1238
#define String_Cancelling               1239
#define String_Cancelled                1240
#define String_NotApplicableDriver      1241
#define String_PreparingFiles           1242
#define String_InstallingEdge           1243
#define String_NotInstalled             1244
#define String_CheckingEdgeVersions     1245
#define String_EdgeVersionStrings       1246
#define String_InstallEdge              1247
#define String_ScaningDrivers           1248
#define String_AddDriverFromInstalledOS 1249
#define String_SelectAll                1250
#define String_SelectInvert             1251
#define String_DriverDetail             1252
#define String_Export                   1253
#define String_ExportingDriver          1254
#define String_KeepClassAndProvider     1255
#define String_ExportToTempDirAndAdd    1256
#define String_ViewOtherUpdates         1257
#define String_ScaningSystems           1258
#define String_SelectAnOS               1259
#define String_DriversNotFound          1260
#define String_NoDrivers                1261
#define String_NoneCompression          1262
#define String_FastCompression          1263
#define String_MaxCompression           1264
#define String_ExtremeCompression       1265
#define String_SelectCompression        1266
#define String_SplitImage               1267
#define String_SelectEditions           1268
#define String_InstallApps              1269
#define String_InstallDotNetFx3         1270
#define String_NoLegacyBoot             1271
#define String_NoUefiBoot               1272
#define String_UefiBootSupport          1273
#define String_UefiBootSupportNoPrompt  1274
#define String_UefiOptions              1275
#define String_AddDrivers               1276
#define String_PartSize                 1277
#define String_PartSizeTip              1278
#define String_CdLabel                  1279
#define String_NoSelectedEditions       1280
#define String_NoCdLabel                1281
#define String_MountingImageState       1282
#define String_CommittingImageState     1283
#define String_UnmountingImageState     1284
#define String_ExportingEditionImageState 1285
#define String_SplittingImage           1286
#define String_MountingImage            1287
#define String_CommittingImage          1288
#define String_UnmountingImage          1289
#define String_CleanComponents          1290
#define String_CleanComponentsWarning   1291
#define String_CleaningComponents       1292
#define String_CleaningComponentsState  1293
#define String_SystemDestroyed          1294
#define String_RunOscdimg               1295
#define String_CreatingISOProgress      1296
#define String_NeedLargerPart           1297
#define String_UpgradingEditionState    1298
#define String_ConfiguringBootWim       1299
#define String_ExportingImageState      1300
#define String_UpgradingEdition         1301
#define String_Configuring              1302
#define String_CdLabelTooLong           1303
#define String_ScanningFiles            1304
#define String_CreateISO                1305
#define String_CreateSystemImage        1306
#define String_SynergisticInstallation  1307
#define String_SynergisticInstallationNotice 1308
#define String_SynergisticInstallationIsNotAvaliable 1309
#define String_NoReboot                 1310
#define String_SwitchingEditionForUpgrading 1311
#define String_CantKeepDataAndSettings  1312
#define String_CleanDowngrade           1313
#define String_MediaSetupNotice         1314
#define String_KeepDataAndApps          1315
#define String_DataOnly                 1316
#define String_CleanInstallation        1317
#define String_ViewSetupReport          1318
#define String_SkipCompatScan           1319
#define String_IgnoreWarnings           1320
#define String_RunningCompactibilityScans 1321
#define String_RemoveHwReq              1322
#define File_Bootloader                 14465
#define File_NtfsBootmgrLdr             14466
#define File_ExfatBootmgrLdr            14467
#define File_Fat32BootmgrLdr            14468
#define File_FatBootmgrLdr              14469
#define File_EmptyESD                   14470
#define File_FakeSetupHost              14471
#define File_FakeWimgAPI                14472
#define File_OscdimgCAB                 14473
#define File_DllFdHookAmd64             14474
#define File_DllFdHookArm64             14475
#define File_FakeAutoRunAmd64           14476
#define File_FakeAutoRunArm64           14477
#define ID_40001                        40001
#define ID_40002                        40002
#define ID_40003                        40003
#define ID_40004                        40004
#define ID_40005                        40005
#define ID_40006                        40006
#define ID_40007                        40007
#define ID_40008                        40008
#define ID_40009                        40009
#define ID_40010                        40010
#define ID_40011                        40011
#define ID_40012                        40012
#define ID_40013                        40013
#define ID_40014                        40014
#define ID_40015                        40015
#define String_AppName                  50000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40016
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
