#include "pch.h"
#include "Configuration.h"

#include <fstream>
#include <iostream>
#include <nlohmann/json.hpp>
#include <filesystem>

using namespace std;

bool Configuration::Load(const char* FilePath)
{
    try
    {
        std::ifstream file(FilePath);
        if (!file.is_open())
        {
            std::cerr << "Failed to open configuration file: " << FilePath << std::endl;
            return false;
        }

        nlohmann::json json;
        file >> json;

        if (!json.is_object())
        {
            std::cerr << "Invalid JSON format in configuration file: " << FilePath << std::endl;
            return false;
        }

        if (json.contains("UseCRLF"))
            UseCRLF = json["UseCRLF"].get<bool>();

        auto features = json.find("Features");
        if (features != json.end() && features->is_array())
        {
            for (const auto& feature : *features)
            {
                if (feature.is_object() && feature.contains("Id") && feature.contains("Macro"))
                {
                    FeatureItem item;
                    item.Name = feature.value("Name", "");
                    item.Description = feature.value("Description", "");
                    item.Macro = feature["Macro"].get<std::string>();
                    item.Value = feature.value("Value", "");
                    item.Enable = feature.value("Default", false);
                    auto Id = feature["Id"].get<std::string>();
                    
                    FeatureMap[move(Id)] = move(item);
                }
            }
        }
        else
        {
            std::cerr << "No valid Features found in configuration file: " << FilePath << std::endl;
            return false;
        }
    }
    catch (const std::exception& e)
    {
        std::cerr << "Error loading configuration: " << e.what() << std::endl;
        return false;
    }
    return true;
}

std::string Configuration::GetFeatureHeader(const FeatureManager& Features)
{
    const PCSTR NewLine = UseCRLF ? "\r\n" : "\n";

    std::string HeaderContent;
    HeaderContent.reserve(1024);
    HeaderContent = "// Generated by Lourdle Configuration Tool. Do not edit manually.";
    HeaderContent += NewLine;
    HeaderContent += NewLine;
    HeaderContent += "#ifndef GLOBAL_FEATURES_H";
    HeaderContent += NewLine;
    HeaderContent += "#define GLOBAL_FEATURES_H";
    HeaderContent += NewLine;
    HeaderContent += NewLine;

    for (const auto& Feature : Features)
    {
        auto it = FeatureMap.find(Feature.first);
        if (it == FeatureMap.end())
        {
            std::cerr << "Feature not found in map: " << Feature.first << std::endl;
            continue;
        }
        FeatureItem& Item = it->second;
        Item.Enable = Feature.second;
        cout << "Feature: " << Feature.first << " set to " << (Item.Enable ? "Enabled" : "Disabled") << std::endl;
    }

    for (const auto& Feature : FeatureMap)
    {
        const FeatureItem& Item = Feature.second;

        std::cout << "Feature: " << Feature.first << "..." << (Item.Enable ? "Enabled" : "Disabled") << std::endl;

        if (!Item.Enable)
            continue;

        if (!Item.Name.empty())
            HeaderContent += "// " + Item.Name + NewLine;
        if (!Item.Description.empty())
            HeaderContent += "// " + Item.Description + NewLine;
        HeaderContent += "#define " + Item.Macro;
        if (!Item.Value.empty())
            HeaderContent += " " + Item.Value;
        HeaderContent += NewLine;
    }

    HeaderContent += NewLine;
    HeaderContent += "#endif // GLOBAL_FEATURES_H";
    HeaderContent += NewLine;

    return HeaderContent;
}

bool FeatureManager::Load(const char* FilePath)
{
    std::ifstream FileStream(FilePath);
    if (!FileStream.is_open())
    {
        std::cerr << "Failed to open feature file: " << FilePath << std::endl;
        return false;
    }

    string Line;
    while (getline(FileStream, Line))
    {
        if (Line.empty() || Line[0] == '#')
            continue;
        size_t EqualPos = Line.find('=');
        if (EqualPos == string::npos)
        {
            std::cerr << "Invalid feature line: " << Line << std::endl;
            continue;
        }
        string FeaturId = Line.substr(0, EqualPos);
        string Enable = Line.substr(EqualPos + 1);
        
        bool Status;
        if (_stricmp(Enable.c_str(), "y") == 0
            || _stricmp(Enable.c_str(), "yes") == 0
            || _stricmp(Enable.c_str(), "true") == 0
            || _stricmp(Enable.c_str(), "1") == 0
            || _stricmp(Enable.c_str(), "on") == 0)
            Status = true;
        else if (_stricmp(Enable.c_str(), "n") == 0
            || _stricmp(Enable.c_str(), "no") == 0
            || _stricmp(Enable.c_str(), "false") == 0
            || _stricmp(Enable.c_str(), "0") == 0
            || _stricmp(Enable.c_str(), "off") == 0)
            Status = false;
        else
        {
            std::cerr << "Invalid feature status: " << Enable << " in line: " << Line << "\r\nSkipping...\n";
            continue;
        }
        Features[move(FeaturId)] = Status;
    }
    return true;
}
